# Enforce new panes to inherit paths
bind c new-window -c "#{pane_current_path}"
bind ^ split-window -h -c "#{pane_current_path}" \; run-shell "tmux resize-pane -x 70"
bind '"' split-window -c "#{pane_current_path}"
bind %   split-window -h -c "#{pane_current_path}"

# Send ctrl+o to claude
# bind -n C-o send-keys C-o
# bind -n C-o clear-history

# set -g default-terminal "tmux-256color"
set -g default-terminal "xterm-256color"
set -as terminal-overrides ',*:Tc'

set -g mouse on
# set-option -s set-clipboard off
setw -g mode-keys vi
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection c"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

set -s escape-time 10
set-window-option -g window-status-current-style fg=white,bg=black
set -g status-bg color60
# set -g status-fg black

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
